color_scheme: custom
nav_sort: case_sensitive
remote_theme: pmarsceill/just-the-docs

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2021 Microsoft"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
